name: Metrics
on:
  schedule:
    - cron: "0 0 * * *" # Обновление раз в день
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.GH_METRICS_TOKEN }}
          user: shevavarya
          template: classic
          base: header, activity, community, repositories
          config_timezone: Europe/Moscow
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_repositories: yes
          plugin_repositories_featured: shevavarya/Hand-Hunter, shevavarya/Playlist-Maker
          plugin_lines: yes
          plugin_traffic: yes
