name: Metrics
on:
  schedule:
    - cron: "0 0 * * *" # Обновление раз в день
  workflow_dispatch:
  
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: shevavarya
          template: classic
          base: header, activity, community, repositories
